spring.application.name=sandbox

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Optional: if you want to set a specific dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Liquibase Configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
# Optional: You can also specify liquibase contexts and should you want to
# spring.liquibase.default-schema=your_default_schema # Uncomment and specify if using schemas
# spring.liquibase.enabled=true # This can be set to false if you want to disable

# MyBatis Configuration
mybatis.mapper-locations=classpath:mappers/*.xml
# mybatis.type-aliases-package=com.sandbox.model   # Package where your model classes reside